update

diff --git a/bin/backup2 b/bin/backup2
--- a/bin/backup2
+++ b/bin/backup2
@@ -4,7 +4,7 @@
 #
 # File:		backup
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Wed Aug 23 05:17:45 EDT 2006
+# Date:		Wed Aug 23 05:24:34 EDT 2006
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2006/08/23 09:18:27 $
+#   $Date: 2006/08/23 09:24:37 $
 #   $RCSfile: backup2,v $
-#   $Revision: 1.12 $
+#   $Revision: 1.13 $
 
 case "$1" in
 -doc* )
@@ -183,6 +183,17 @@ do
 
 	    if test "${!remote}" != ""
 	    then
+
+		# Be sure efm starts properly before
+		# calling efm listed.
+
+		efm start
+		if test $? -ne 0
+		then
+		    echo "ERROR starting efm"
+		    exit 1
+		fi
+
 		if efm listed $t
 		then
 		    echo efm remove "${!remote}" $t
