update

diff --git a/bin/backcp b/bin/backcp
--- a/bin/backcp
+++ b/bin/backcp
@@ -4,7 +4,7 @@
 #
 # File:		backcp
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Mon Mar 23 11:26:55 EDT 2009
+# Date:		Mon Mar 23 12:03:36 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/23 15:38:29 $
+#   $Date: 2009/03/23 16:28:17 $
 #   $RCSfile: backcp,v $
-#   $Revision: 1.2 $
+#   $Revision: 1.3 $
 
 case "$1" in
 -doc*)
@@ -207,6 +207,25 @@ esac
 case "$1" in
 
 copyto)
+
+    if [ ! -d "$PARENT" ]
+    then
+	echo "ERROR: $PARENT is not an extant directory"
+	exit 2
+    fi
+
+    if [ `expr "$SIZE" : '[1-9][0-9]*$'` -eq 0 ]
+    then
+	echo "ERROR: bad SIZE: $SIZE"
+	exit 2
+    fi
+
+    if [ `expr "$CAPACITY" : '[1-9][0-9]*$'` -eq 0 ]
+    then
+	echo "ERROR: bad CAPACITY: $CAPACITY"
+	exit 2
+    fi
+
     used="`du -s -B 1MB "$PARENT" | cut -f1`"
     if [ $used -gt "$CAPACITY" ]
     then
