update

diff --git a/bin/cvsadd b/bin/cvsadd
--- a/bin/cvsadd
+++ b/bin/cvsadd
@@ -4,7 +4,7 @@
 #
 # File:		cvsadd
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Fri Mar 27 11:07:47 EDT 2009
+# Date:		Thu Apr  2 18:03:04 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/27 15:17:02 $
+#   $Date: 2009/04/02 22:12:12 $
 #   $RCSfile: cvsadd,v $
-#   $Revision: 1.1 $
+#   $Revision: 1.2 $
 
 # Redirect all error output to the standard output.
 #
@@ -24,19 +24,28 @@ exec 2>&1
 case "$1" in
 -doc*)
     echo '
-cvsadd file_or_directory ...
+cvsadd file_or_subdirectory ...
 
-    Add existing local files and directories to an
-    existing repository.
+    Add existing local files and subdirectories of the
+    current directory to the CVS repository containing
+    the current directory.
 
     Files are NOT committed by this command: they must
     be cvscom'"'"'ed after being `cvsadd'"'"'ed.' \
     ' However, added
-    directories per se do not have to be committed
-    later; only the files in these directories.'
+    subdirectories do not have to be committed later,
+    though the contents of these subdirectories are NOT
+    added to the repository (cvsadd is NOT recursive).'
 
     exit 1
     ;;
 esac
+
+if [ ! -d ./CVS ]
+then
+    echo "ERROR: current directory is not under CVS" \
+         "control"
+    exit 2
+fi
 
 cvs add "$@"
