update

diff --git a/bin/cvscp b/bin/cvscp
--- a/bin/cvscp
+++ b/bin/cvscp
@@ -4,7 +4,7 @@
 #
 # File:		cvscp
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Wed Mar 25 11:40:33 EDT 2009
+# Date:		Fri Mar 27 06:42:13 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/25 18:05:14 $
+#   $Date: 2009/03/27 13:56:23 $
 #   $RCSfile: cvscp,v $
-#   $Revision: 1.5 $
+#   $Revision: 1.6 $
 
 # Redirect all error output to the standard output.
 #
@@ -36,10 +36,20 @@ cvscp file1 file2
     repository file2,v.  After the copy a cvs update is
     performed on file2 to make a local copy.  Lastly
     this local copy is made user writable if file1 was
-    writable before it was committed.'
+    writable before it was committed.
+
+    For cvscp the current directory need not be under
+    CVS control and the two files may be in different
+    CVS repositories as long as both are in the same
+    account.'
     exit 1
     ;;
 esac
+
+dir1="`dirname "$1"`"
+base1="`basename "$1"`"
+dir2="`dirname "$2"`"
+base2="`basename "$2"`"
 
 if [ ! -f "$1" ]
 then
@@ -49,13 +59,13 @@ elif [ -e "$2" ]
 then
     echo "ERROR $2 already exists"
     exit 2
-elif [ ! -d "`dirname "$1"`/CVS ]
+elif [ ! -d "$dir1/CVS" ]
 then
-    echo "ERROR $1 is NOT in a CVS directory"
+    echo "ERROR $dir1 is NOT under CVS control"
     exit 2
-elif [ ! -d "`dirname "$2"`/CVS ]
+elif [ ! -d "$dir2/CVS" ]
 then
-    echo "ERROR $2 is NOT in a CVS directory"
+    echo "ERROR $dir2 is NOT under CVS control"
     exit 2
 fi
 
@@ -65,40 +75,96 @@ then
     w=yes
 fi
 
-echo cvs commit -m update "$1"
-cvs commit -m update "$1"
+echo "(cd $dir1; cvs commit -m update $base1)"
+(cd "$dir1"; cvs commit -m update "$base1")
 
-root="`cat CVS/Root`"
-repository="`cat CVS/Repository`"
-case "$root" in
+root1="`cat "$dir1/CVS/Root"`"
+repository1="`cat "$dir1/CVS/Repository"`"
+rdir1="$root1"
+raccount1=
+case "$root1" in
 *:*)
-    account="`expr "$root" : '\([^:]*\):' `"
-    root="`expr "$root" : '[^:]*:\(.*\)$' `"
-    dir="$root/$repository"
-    echo ssh "$account" cp -p "$dir/$1,v" "$dir/$2,v"
-    if ! ssh "$account" cp -p "$dir/$1,v" "$dir/$2,v"
-    then
-    	echo "ERROR: copy inside repository failed"
-    	exit 2
-    fi
+    raccount1="`expr "$root1" : '\([^:]*\):' `"
+    rdir1="`expr "$root1" : '[^:]*:\(.*\)$' `"
     ;;
+esac
+rdir1="$rdir1/$repository1"
+case "$raccount1" in
+*@*)
+    ;;
+*)
+    echo "ERROR: bad $dir1/CVS/Root: $root1"
+    exit 2
+    ;;
+esac
+case "$rdir1" in
 /*)
-    dir="$root/$repository"
-    echo cp -p "$dir/$1,v" "$dir/$2,v"
-    if ! cp -p "$dir/$1,v" "$dir/$2,v"
+    ;;
+*)
+    echo "ERROR: bad $dir1/CVS/Root: $root1"
+    exit 2
+    ;;
+esac
+
+root2="`cat "$dir2/CVS/Root"`"
+repository2="`cat "$dir2/CVS/Repository"`"
+rdir2="$root2"
+raccount2=
+case "$root2" in
+*:*)
+    raccount2="`expr "$root2" : '\([^:]*\):' `"
+    rdir2="`expr "$root2" : '[^:]*:\(.*\)$' `"
+    ;;
+esac
+rdir2="$rdir2/$repository2"
+case "$raccount2" in
+*@*)
+    ;;
+*)
+    echo "ERROR: bad $dir2/CVS/Root: $root2"
+    exit 2
+    ;;
+esac
+case "$rdir2" in
+/*)
+    ;;
+*)
+    echo "ERROR: bad $dir2/CVS/Root: $root2"
+    exit 2
+    ;;
+esac
+
+if [ "$raccount1" != "$raccount2" ]
+then
+    echo "ERROR: $dir1/CVS/Root account ($raccount1)" \
+         "!= $dir2/CVS/Root account ($raccount2)"
+    exit 2
+fi
+
+
+rfile1="$rdir1/$base1,v"
+rfile2="$rdir2/$base2,v"
+case "$raccount1" in
+"")
+    echo cp -p "$rfile1" "$rfile1"
+    if ! cp -p "$rfile1" "$rfile1"
     then
     	echo "ERROR: copy inside repository failed"
     	exit 2
     fi
     ;;
 *)
-    echo "ERROR: bad CVS/Root value: $root"
-    exit 2
+    echo ssh "$raccount1" cp -p "$rfile1" "$rfile2"
+    if ! ssh "$raccount1" cp -p "$rfile1" "$rfile2"
+    then
+    	echo "ERROR: copy inside repository failed"
+    	exit 2
+    fi
     ;;
 esac
 
-echo cvs update "$2"
-cvs update "$2"
+echo "(cd $dir2; cvs update $base2)"
+(cd "$dir2"; cvs update "$base2")
 
 if [ w = yes ]
 then
diff --git a/bin/cvsexpunge b/bin/cvsexpunge
--- a/bin/cvsexpunge
+++ b/bin/cvsexpunge
@@ -4,7 +4,7 @@
 #
 # File:		cvsrm
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Thu Mar 26 12:25:10 EDT 2009
+# Date:		Fri Mar 27 06:41:59 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/26 19:58:33 $
+#   $Date: 2009/03/27 13:56:23 $
 #   $RCSfile: cvsexpunge,v $
-#   $Revision: 1.1 $
+#   $Revision: 1.2 $
 
 # Redirect all error output to the standard output.
 #
@@ -38,7 +38,13 @@ cvsrm [-f] file ...
     records of the file.
 
     Without the -f option, the user is asked to approve
-    each file removal.'
+    each file removal.
+
+    Cvsrm does not require that the current directory
+    be under CVS control or that given files be in the
+    same repository.  Directories cannot be removed by
+    cvsrm.'
+
     exit 1
     ;;
 -f)
@@ -49,25 +55,53 @@ esac
 
 for file in "$@"
 do
-    fdir="`dirname "$file"`"
-    fbase="`basename "$file"`"
+    dir="`dirname "$file"`"
+    base="`basename "$file"`"
     if [ ! -f "$file" ]
     then
 	echo "ERROR $file is NOT an ordinary file;" \
 	     "skipping"
 	continue
-    elif [ ! -d "$fdir/CVS" ]
+    elif [ ! -d "$dir/CVS" ]
     then
-	echo "ERROR $file is NOT in a CVS controlled" \
+	echo "ERROR $dir is NOT a CVS controlled" \
 	     "directory; skipping"
 	continue
-    elif ! (cd $fdir; \
-            cvs log $fbase >/dev/null 2>/dev/null)
+    elif ! (cd "$dir"; \
+            cvs log "$base" >/dev/null 2>/dev/null)
     then
 	echo "ERROR: $file is not in repository;" \
 	     "skipping"
 	continue
     fi
+
+    root="`cat "$dir/CVS/Root"`"
+    repository="`cat "$dir/CVS/Repository"`"
+    rdir="$root"
+    raccount=
+    case "$root" in
+    *:*)
+	raccount="`expr "$root" : '\([^:]*\):' `"
+	rdir="`expr "$root" : '[^:]*:\(.*\)$' `"
+	;;
+    esac
+    rdir="$rdir/$repository"
+    case "$raccount" in
+    *@*)
+	;;
+    *)
+	echo "ERROR: bad $dir/CVS/Root: $root"
+	exit 2
+	;;
+    esac
+    case "$rdir" in
+    /*)
+	;;
+    *)
+	echo "ERROR: bad $dir/CVS/Root: $root"
+	exit 2
+	;;
+    esac
 
     if [ $f = no ]
     then
@@ -78,51 +112,56 @@ do
 	fi
     fi
 
-    root="`cat "$fdir/CVS/Root"`"
-    repository="`cat "$fdir/CVS/Repository"`"
-    case "$root" in
-    *:*)
-	account="`expr "$root" : '\([^:]*\):' `"
-	root="`expr "$root" : '[^:]*:\(.*\)$' `"
-	rdir="$root/$repository"
-	case "$root" in
-	/*) ;;
-	*)  echo "ERROR: bad $file CVS/Root value" \
-	         "$root; skipping"
-	    continue
-	    ;;
-	esac
-	if ! ssh "$account" test -f "$rdir/$fbase,v"
+    case "$raccount" in
+    "")
+	if [ -f "$rdir/$base,v" ]
 	then
-	    ## Added but not committed
-	    echo "(cd $fdir; cvs remove -f $fbase)"
-	    (cd $fdir; cvs remove -f $fbase)
+	    echo rm -f "$rdir/$base,v"
+	    rm -f "$rdir/$base,v"
+	    echo rm -f "$file"
+	    rm -f "$file"
+	    echo "(cd $dir; cvs update $base)"
+	    (cd "$dir"; cvs update "$base")
+	elif [ -f "$rdir/Attic/$base,v" ]
+	then
+	    ## in the Attic
+	    echo rm -f "$rdir/Attic/$base,v"
+	    rm -f "$rdir/Attic/$base,v"
+	    echo rm -f "$file"
+	    rm -f "$file"
+	    echo "(cd $dir; cvs update $base)"
+	    (cd "$dir"; cvs update "$base")
 	else
-	    echo ssh "$account" rm -f "$rdir/$fbase,v"
-	    ssh "$account" rm -f "$rdir/$fbase,v"
-	    rm -f $file
-	    echo "(cd $fdir; cvs update $fbase)"
-	    (cd $fdir; cvs update $fbase)
-	fi
-	;;
-    /*)
-	rdir="$root/$repository"
-	if [ ! -f "$rdir/$fbase,v" ]
-	then
 	    ## Added but not committed.
-	    echo "(cd $fdir; cvs remove -f $fbase)"
-	    (cd $fdir; cvs remove -f $fbase)
-	else
-	    rm -f "$rdir/$fbase,v"
-	    rm -f $file
-	    echo "(cd $fdir; cvs update $fbase)"
-	    (cd $fdir; cvs update $fbase)
+	    echo "(cd $dir; cvs remove -f $base)"
+	    (cd $dir; cvs remove -f $base)
 	fi
 	;;
     *)
-	echo "ERROR: bad $file CVS/Root value $root;" \
-	     "skipping"
-	continue
+	if ssh "$raccount" test -f "$rdir/$base,v"
+	then
+	    echo ssh "$raccount" rm -f "$rdir/$base,v"
+	    ssh "$raccount" rm -f "$rdir/$base,v"
+	    echo rm -f "$file"
+	    rm -f "$file"
+	    echo "(cd $dir; cvs update $base)"
+	    (cd "$dir"; cvs update "$base")
+	elif ssh "$raccount" test -f \
+	         "$rdir/Attic/$base,v"
+	then
+	    ## in the Attic
+	    echo ssh "$raccount" \
+	         rm -f "$rdir/Attic/$base,v"
+	    ssh "$raccount" rm -f "$rdir/Attic/$base,v"
+	    echo rm -f "$file"
+	    rm -f "$file"
+	    echo "(cd $dir; cvs update $base)"
+	    (cd "$dir"; cvs update "$base")
+	else
+	    ## Added but not committed
+	    echo "(cd $dir; cvs remove -f $base)"
+	    (cd $dir; cvs remove -f $base)
+	fi
 	;;
     esac
 
