update

diff --git a/bin/cvscp b/bin/cvscp
--- a/bin/cvscp
+++ b/bin/cvscp
@@ -4,7 +4,7 @@
 #
 # File:		cvscp
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Tue Mar 31 10:22:21 EDT 2009
+# Date:		Tue Mar 31 11:28:52 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/31 14:34:12 $
+#   $Date: 2009/03/31 15:29:30 $
 #   $RCSfile: cvscp,v $
-#   $Revision: 1.8 $
+#   $Revision: 1.9 $
 
 # Redirect all error output to the standard output.
 #
@@ -78,7 +78,11 @@ then
 fi
 
 echo "(cd $dir1; cvs commit -m update $base1)"
-(cd "$dir1"; cvs commit -m update "$base1")
+if ! (cd "$dir1"; cvs commit -m update "$base1")
+then
+    echo "ERROR: while committing $dir1/$base1"
+    exit 2
+fi
 
 root1="`cat "$dir1/CVS/Root"`"
 repository1="`cat "$dir1/CVS/Repository"`"
diff --git a/bin/cvsmv b/bin/cvsmv
--- a/bin/cvsmv
+++ b/bin/cvsmv
@@ -4,7 +4,7 @@
 #
 # File:		cvsmv
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Tue Mar 31 11:21:46 EDT 2009
+# Date:		Tue Mar 31 11:29:03 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/31 15:22:17 $
+#   $Date: 2009/03/31 15:29:30 $
 #   $RCSfile: cvsmv,v $
-#   $Revision: 1.8 $
+#   $Revision: 1.9 $
 
 # Redirect all error output to the standard output.
 #
@@ -81,7 +81,11 @@ then
 fi
 
 echo "(cd $dir1; cvs commit -m update $base1)"
-(cd "$dir1"; cvs commit -m update "$base1")
+if ! (cd "$dir1"; cvs commit -m update "$base1")
+then
+    echo "ERROR: while committing $dir1/$base1"
+    exit 2
+fi
 
 root1="`cat "$dir1/CVS/Root"`"
 repository1="`cat "$dir1/CVS/Repository"`"
diff --git a/bin/cvsrm b/bin/cvsrm
--- a/bin/cvsrm
+++ b/bin/cvsrm
@@ -4,7 +4,7 @@
 #
 # File:		cvsrm
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Mon Mar 30 08:26:16 EDT 2009
+# Date:		Tue Mar 31 11:24:13 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/30 12:30:36 $
+#   $Date: 2009/03/31 15:29:30 $
 #   $RCSfile: cvsrm,v $
-#   $Revision: 1.3 $
+#   $Revision: 1.4 $
 
 # Redirect all error output to the standard output.
 #
@@ -41,6 +41,13 @@ cvsrm file ...
     exit 1
     ;;
 esac
+
+echo cvs commit -m update "$@"
+if ! cvs commit -m update "$@"
+then
+    echo "ERROR: while committing files before removing"
+    exit 2
+fi
 
 echo cvs remove -f "$@"
 cvs remove -f "$@"
