update

diff --git a/bin/cvsdiff b/bin/cvsdiff
--- a/bin/cvsdiff
+++ b/bin/cvsdiff
@@ -4,7 +4,7 @@
 #
 # File:		cvsdiff
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Tue Mar 31 07:37:08 EDT 2009
+# Date:		Thu Apr  2 19:23:37 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/31 11:42:07 $
+#   $Date: 2009/04/02 23:24:17 $
 #   $RCSfile: cvsdiff,v $
-#   $Revision: 1.7 $
+#   $Revision: 1.8 $
 
 # Redirect all error output to the standard output.
 #
@@ -63,5 +63,12 @@ cvsdiff [options] [file_or_directory ...]
     exit 1
     ;;
 esac
+
+if [ ! -d ./CVS ]
+then
+    echo "ERROR: current directory is not under CVS" \
+         "control"
+    exit 2
+fi
 
 cvs diff "$@" 2>&1 | grep -v 'cvs.*: Diffing '
