update

diff --git a/bin/cvsexpunge b/bin/cvsexpunge
--- a/bin/cvsexpunge
+++ b/bin/cvsexpunge
@@ -4,7 +4,7 @@
 #
 # File:		cvsexpunge
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Mon Mar 30 08:19:18 EDT 2009
+# Date:		Mon Mar 30 14:18:13 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/30 12:25:13 $
+#   $Date: 2009/03/30 18:18:20 $
 #   $RCSfile: cvsexpunge,v $
-#   $Revision: 1.4 $
+#   $Revision: 1.5 $
 
 # Redirect all error output to the standard output.
 #
@@ -30,13 +30,15 @@ cvsexpunge [-f] file ...
     Expunge files from both the local directories and
     the repository.  Once expunged, these files CANNOT
     be recovered, and tagged revisions of the files are
-    permanently lost.  A local copy of a file must exist
-    in order to expunge the file from the repository.
+    permanently lost.  A local copy of a file need not
+    exist in order to expunge the file from the reposi-
+    tory.
 
     More specifically, each file is removed both from
     the repository, including any Attic directories, and
     from the local directory, and then `cvsup file'"'"'
-    is executed to remove local CVS records of the file.
+    is executed if necessary to remove local CVS records
+    of the file.
 
     Without the -f option, the user is asked to approve
     each file expungement.
@@ -58,9 +60,14 @@ for file in "$@"
 do
     dir="`dirname "$file"`"
     base="`basename "$file"`"
-    if [ ! -f "$file" ]
+    if [ -L "$file" ]
     then
-	echo "ERROR $file is NOT an ordinary file;" \
+	echo "ERROR $file is symbolic link;" \
+	     "skipping"
+	continue
+    elif [ -e "$file" -a ! -f "$file" ]
+    then
+	echo "ERROR $file is not an ordinary file;" \
 	     "skipping"
 	continue
     elif [ ! -d "$dir/CVS" ]
@@ -68,12 +75,12 @@ do
 	echo "ERROR $dir is NOT a CVS controlled" \
 	     "directory; skipping"
 	continue
-    elif ! (cd "$dir"; \
-            cvs log "$base" >/dev/null 2>/dev/null)
+    fi
+
+    e=no
+    if [ -f "$file" ]
     then
-	echo "ERROR: $file is not in repository;" \
-	     "skipping"
-	continue
+        e=yes
     fi
 
     root="`cat "$dir/CVS/Root"`"
@@ -104,34 +111,82 @@ do
 	;;
     esac
 
-    if [ $f = no ]
+    tags=(`cvs log 2>&1 | sed -n -e '
+: look
+/^RCS file: /s///
+t found
+n
+b look
+: found
+x
+/.*/s///
+x
+H
+: infile
+n
+/^symbolic names:$/b readtags
+/^RCS file: /b look
+b infile
+: readtags
+n
+/^	\([^:]*\):.*$/s//\1/
+T done
+H
+b readtags
+: done
+x
+/^\n/s///
+: loop
+/\n/s// /
+t loop
+p
+n
+b look' | egrep "^$rdir/(Attic/|)$base,v" \
+        | cut -d' ' -f2- `)
+
+    if [ ${#tags[@]} -gt 0 ]
     then
-    	echo -n "remove $file (y or n)? "
+        echo "***** WARNING: $file has tags ${tags[@]}"
+    	echo -n "Do you really want to expunge" \
+	        "$file (y or n)? "
+	if ! read || [ "$REPLY" != y ]
+	then
+	    continue
+	fi
+    elif [ $f = no ]
+    then
+    	echo -n "expunge $file (y or n)? "
 	if ! read || [ "$REPLY" != y ]
 	then
 	    continue
 	fi
     fi
-
+    
     case "$raccount" in
     "")
 	if [ -f "$rdir/$base,v" ]
 	then
 	    echo rm -f "$rdir/$base,v"
 	    rm -f "$rdir/$base,v"
-	    echo rm -f "$file"
-	    rm -f "$file"
-	    echo "(cd $dir; cvs update $base)"
-	    (cd "$dir"; cvs update "$base")
+	    if [ $e = yes ]
+	    then
+		echo rm -f "$file"
+		rm -f "$file"
+		echo "(cd $dir; cvs update $base)"
+		(cd "$dir"; cvs update "$base")
+	    fi
 	elif [ -f "$rdir/Attic/$base,v" ]
 	then
 	    ## in the Attic
 	    echo rm -f "$rdir/Attic/$base,v"
 	    rm -f "$rdir/Attic/$base,v"
-	    echo rm -f "$file"
-	    rm -f "$file"
-	    echo "(cd $dir; cvs update $base)"
-	    (cd "$dir"; cvs update "$base")
+	    if [ $e = yes ]
+	    then
+		echo rm -f "$file"
+		rm -f "$file"
+		echo "(cd $dir; cvs update $base)"
+		(cd "$dir"; cvs update "$base")
+	    fi
 	else
 	    ## Added but not committed.
 	    echo "(cd $dir; cvs remove -f $base)"
@@ -143,10 +198,13 @@ do
 	then
 	    echo ssh "$raccount" rm -f "$rdir/$base,v"
 	    ssh "$raccount" rm -f "$rdir/$base,v"
-	    echo rm -f "$file"
-	    rm -f "$file"
-	    echo "(cd $dir; cvs update $base)"
-	    (cd "$dir"; cvs update "$base")
+	    if [ $e = yes ]
+	    then
+		echo rm -f "$file"
+		rm -f "$file"
+		echo "(cd $dir; cvs update $base)"
+		(cd "$dir"; cvs update "$base")
+	    fi
 	elif ssh "$raccount" test -f \
 	         "$rdir/Attic/$base,v"
 	then
@@ -154,10 +212,13 @@ do
 	    echo ssh "$raccount" \
 	         rm -f "$rdir/Attic/$base,v"
 	    ssh "$raccount" rm -f "$rdir/Attic/$base,v"
-	    echo rm -f "$file"
-	    rm -f "$file"
-	    echo "(cd $dir; cvs update $base)"
-	    (cd "$dir"; cvs update "$base")
+	    if [ $e = yes ]
+	    then
+		echo rm -f "$file"
+		rm -f "$file"
+		echo "(cd $dir; cvs update $base)"
+		(cd "$dir"; cvs update "$base")
+	    fi
 	else
 	    ## Added but not committed
 	    echo "(cd $dir; cvs remove -f $base)"
