update

diff --git a/bin/cvsignore b/bin/cvsignore
--- a/bin/cvsignore
+++ b/bin/cvsignore
@@ -4,7 +4,7 @@
 #
 # File:		cvsignore
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Thu Apr  2 19:49:37 EDT 2009
+# Date:		Fri Apr  3 22:35:54 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/04/02 23:50:53 $
+#   $Date: 2009/04/04 02:36:49 $
 #   $RCSfile: cvsignore,v $
-#   $Revision: 1.2 $
+#   $Revision: 1.3 $
 
 # Redirect all error output to the standard output.
 #
@@ -46,6 +46,13 @@ cvsignore file_or_pattern ...
     exit 1
     ;;
 esac
+
+if [ ! -d ./CVS ]
+then
+    echo "ERROR: current directory is not under CVS" \
+         "control"
+    exit 2
+fi
 
 if [ $# -eq 0 ]
 then
diff --git a/bin/cvsup b/bin/cvsup
--- a/bin/cvsup
+++ b/bin/cvsup
@@ -4,7 +4,7 @@
 #
 # File:		cvsup
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Fri Apr  3 21:56:20 EDT 2009
+# Date:		Fri Apr  3 22:37:54 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/04/04 01:57:08 $
+#   $Date: 2009/04/04 02:38:23 $
 #   $RCSfile: cvsup,v $
-#   $Revision: 1.10 $
+#   $Revision: 1.11 $
 
 P=-P
 case "$1" in
@@ -107,5 +107,12 @@ cvsup [-E] [file-or-directory ...]
 	shift
 	;;
 esac
+
+if [ ! -d ./CVS ]
+then
+    echo "ERROR: current directory is not under CVS" \
+         "control"
+    exit 2
+fi
 
 cvs update -d $P "$@" 2>&1 | grep -v ': Updating'
diff --git a/bin/cvsutd b/bin/cvsutd
--- a/bin/cvsutd
+++ b/bin/cvsutd
@@ -4,7 +4,7 @@
 #
 # File:		cvsutd
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Sun Mar 29 16:11:44 EDT 2009
+# Date:		Fri Apr  3 22:38:40 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/29 20:18:54 $
+#   $Date: 2009/04/04 02:39:02 $
 #   $RCSfile: cvsutd,v $
-#   $Revision: 1.6 $
+#   $Revision: 1.7 $
 
 case "$1" in
 
@@ -31,5 +31,12 @@ cvsutd [file-or-directory ...]
     	exit 1
 	;;
 esac
+
+if [ ! -d ./CVS ]
+then
+    echo "ERROR: current directory is not under CVS" \
+         "control"
+    exit 2
+fi
 
 cvs -n update -d -P "$@" 2>&1 | grep -v ': Updating'
