update

diff --git a/bin/cvsold b/bin/cvsold
--- a/bin/cvsold
+++ b/bin/cvsold
@@ -4,7 +4,7 @@
 #
 # File:		cvsold
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Sun Mar 29 08:30:13 EDT 2009
+# Date:		Wed Apr  1 13:04:16 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/29 15:30:25 $
+#   $Date: 2009/04/01 17:04:27 $
 #   $RCSfile: cvsold,v $
-#   $Revision: 1.2 $
+#   $Revision: 1.3 $
 
 case "$1" in
 
@@ -39,7 +39,14 @@ r*) ;;
     ;;
 esac
 
+if [ $# != 2 ]
+then
+    echo "ERROR: too few or too many arguments"
+    exit 2
+fi
+
 rm -f "$2.$1"
-cvs update "-$1" "$2" > "$2.$1"
+echo "cvs update -$1 -p $2 > $2.$1"
+cvs update "-$1" -p "$2" > "$2.$1"
 echo chmod a-w "$2.$1"
 chmod a-w "$2.$1"
