update

diff --git a/bin/cvsold b/bin/cvsold
--- a/bin/cvsold
+++ b/bin/cvsold
@@ -4,7 +4,7 @@
 #
 # File:		cvsold
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Wed Apr  1 13:04:16 EDT 2009
+# Date:		Thu Apr  2 21:20:43 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/04/01 17:04:27 $
+#   $Date: 2009/04/03 01:24:33 $
 #   $RCSfile: cvsold,v $
-#   $Revision: 1.3 $
+#   $Revision: 1.4 $
 
 case "$1" in
 
@@ -32,6 +32,13 @@ cvsold [rX.Y|rT] file
 	;;
 esac
 
+if [ ! -d ./CVS ]
+then
+    echo "ERROR: current directory is not under CVS" \
+         "control"
+    exit 2
+fi
+
 case "$1" in
 r*) ;;
 *)  echo "ERROR: bad revision format: $1"
@@ -47,6 +54,10 @@ fi
 
 rm -f "$2.$1"
 echo "cvs update -$1 -p $2 > $2.$1"
-cvs update "-$1" -p "$2" > "$2.$1"
-echo chmod a-w "$2.$1"
-chmod a-w "$2.$1"
+if cvs update "-$1" -p "$2" > "$2.$1"
+then
+    echo chmod a-w "$2.$1"
+    chmod a-w "$2.$1"
+else
+    rm -f "$2.$1"
+fi
