update

diff --git a/bin/cvsout b/bin/cvsout
--- a/bin/cvsout
+++ b/bin/cvsout
@@ -1,10 +1,10 @@
-#! /bin/csh -fe
+#!/bin/sh
 #
 # Create new project directory.
 #
 # File:		cvsout
 # Author:	Bob Walton <walton@deas.harvard.edu>
-# Date:		Wed Jun 25 12:11:07 EDT 2003
+# Date:		Tue Mar 24 08:38:10 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,90 +13,152 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2003/06/25 16:11:59 $
+#   $Date: 2009/03/24 14:12:33 $
 #   $RCSfile: cvsout,v $
-#   $Revision: 1.2 $
+#   $Revision: 1.3 $
 
-switch ( "$1" )
+n=no
+e=no
+case "$1" in
 
-   case -doc*:
+-doc*)
 
-   	echo "\
-cvsout -d repository-name [-n | -e] directory\
-\
-    Checkout a repository directory.  If the -n option\
-    is given and the directory does not exist in the \
-    repository, the directory is made in the reposi-\
-    tory.  Unless the -e option is given, the directory\
-    must not exist locally, as it will be made locally\
-    as per "'`'"mkdir directory'.  You can use\
-\
-	cvsout -d repository-name -e .\
-\
-    to checkout the entire repository to the current\
-    directory.  If the -e option is given, the existing\
-    local directory may already contain files, which" \
-    	"are\
-    not disturbed if they are not in the repository.\
-\
-    This command should NOT be used to make a new sub-\
-    directory of an already checked out directory.\
-    In that case use "'`'"mkdir directory' followed by\
-\
-	cvs add directory\
-"
+    echo '
+cvsout [-n|-e|-ne|-en] repository directory
 
+    Checkout a directory from a repository.
 
-    	exit 1
-	breaksw
-    case -d:
-        breaksw
-    default:
-        echo "ERROR: first argument must be -d"
-	exit 1
-endsw
+    The repository argument is of the form
 
-switch ( "$3" )
-    case -e:
-        if ( "$5" != "" ) then
-	    echo "ERROR: cannot understand $3 $4 $5"
-	    exit 1
-	endif
-	set e=yes
-        set n=no
-	set d="$4"
-	breaksw
-    case -n:
-        if ( "$5" != "" ) then
-	    echo "ERROR: cannot understand $3 $4 $5"
-	    exit 1
-	endif
-	set e=no
-        set n=yes
-	set d="$4"
-	breaksw
-    default:
-        if ( "$4" != "" ) then
-	    echo "ERROR: cannot understand $3 $4"
-	    exit 1
-	endif
+    	AAA@HHH:DDD
 
-	set e=no
-        set n=no
-	set d="$3"
-	breaksw
-endsw
+    where AAA is an account name, HHH is the name of the
+    host on which the account resides, and DDD is the
+    ABSOLUTE pathname of the root directory holding the
+    repository within the account AAA@HHH.
+    
+    Then `directory'"'"' is both the name of the subdir-
+    ctory of DDD being checked out, relative to DDD, and
+    ALSO the name of the local checked out copy direc-
+    tory, relative to the current directory.  AFTER
+    checkout you can rename the local checked out copy
+    directory if you like.
 
+    If DDD is in the current account, `AAA@HHH:'"'"'
+    should be omitted.
 
-if ( "$e" == "no" ) then
-    mkdir "$d"
-else if ( ! -d "$d" ) then
-    echo "ERROR: $d is not an existing directory"
+    All the contents of a directory being checked out
+    will be checked out, recursively.
+
+    Normally `directory'"'"' must exist in the reposi-
+    tory but must NOT exist locally, and it will be
+    checked out, thus creating it locally.
+
+    If the -e option is given, the directory must pre-
+    exist locally, but it also must NOT contain any
+    contents with the same names as contents being
+    checked out.
+
+    If the -n option is given the directory must not
+    exist in the repository, and will be created there.
+    In this case the repository directory will be empty
+    and have no contents to check out.
+
+    The -ne or -en options combine the action of -e and
+    -n and can be used to make an existing directory
+    into a repository directory.  The contents of the
+    existing directory are NOT entered into the
+    repository: use cvsadd to do this.
+
+    This command should NOT be used if the directory is
+    or will be a previously checked out directory or
+    inside a previously checked out directory.  In
+    that case use cvsdir instead.'
+
     exit 1
-endif
+    ;;
+-n)
+    shift
+    n=yes
+    ;;
+-e)
+    shift
+    e=yes
+    ;;
+-ne|-en)
+    shift
+    n=yes
+    e=yes
+    ;;
+esac
 
-if ( "$n" == "yes" ) then
-    ( cd "$d"; cvs -d "$2" import -m initialize \
-			   "$d" `basename ~` initial )
-endif
-cvs -d "$2" checkout "$d"
+if [ $# -ne 2 ]
+then
+    echo "ERROR: too few or too many arguments"
+    exit 2
+fi
+
+repository="$1"
+directory="$2"
+
+case "$repository" in
+*:*)
+    remote=yes
+    account="`expr "$repository" : '\([^:]*\):'`"
+    root="`expr "$repository" : '[^:]*:\(.*\)$'`"
+    case "$account" in
+    *?@?*)	aok=yes;;
+    *)	echo "ERROR: bad account format: $account"
+        exit 2;;
+    esac
+    case "$root" in
+    /?*)	aok=yes;;
+    *)	echo "ERROR: non-absolute root directory" \
+             "name: $root"
+        exit 2;;
+    esac
+    ;;
+/?*)
+    remote=no
+    ;;
+*)
+    echo "ERROR: bad repository format: $repository"
+    exit 2
+    ;;
+esac
+
+if [ $e = no -a -e "$directory" ]
+then
+    echo "ERROR: local directory exists but no -e" \
+         "option given: $directory"
+    exit 2
+elif [ $e = yes -a ! -d "$directory" ]
+then
+    echo "ERROR: local directory does not exist" \
+         "but -e option given: $directory"
+    exit 2
+fi
+
+if [ $n = yes ]
+then
+    if [ $remote = no ]
+    then
+    	echo mkdir "repository/$directory"
+    	if ! mkdir "repository/$directory"
+	then
+	    echo "ERROR $repository/$directory" \
+	         "already exists"
+	    exit 2
+	fi
+    else
+    	echo ssh "$account" mkdir "$root/$directory"
+    	if ! ssh "$account" mkdir "$root/$directory"
+	then
+	    echo "ERROR $repository:$directory" \
+	         "already exists"
+	    exit 2
+	fi
+    fi
+fi
+
+cvs -d "$repository" checkout "$directory"
