update

diff --git a/bin/cvstagrm b/bin/cvstagrm
--- a/bin/cvstagrm
+++ b/bin/cvstagrm
@@ -4,7 +4,7 @@
 #
 # File:		cvstagrm
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Tue Mar 31 05:12:16 EDT 2009
+# Date:		Tue Mar 31 12:09:12 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/31 11:02:51 $
+#   $Date: 2009/03/31 16:11:28 $
 #   $RCSfile: cvstagrm,v $
-#   $Revision: 1.1 $
+#   $Revision: 1.2 $
 
 # Redirect all error output to the standard output.
 #
@@ -68,10 +68,18 @@ then
 fi
 
 echo cvs commit -m update
-cvs commit -m update
+if ! cvs commit -m update
+then
+    echo "ERROR: commit failed"
+    exit 2
+fi
 
 echo cvs update -d -P
-cvs update -d -P
+if ! cvs update -d -P
+then
+    echo "ERROR: update failed"
+    exit 2
+fi
 
 # The only way to manipulate tags on Attic files is
 # to check them out.
