update

diff --git a/bin/cvstagmv b/bin/cvstagmv
--- a/bin/cvstagmv
+++ b/bin/cvstagmv
@@ -1,10 +1,10 @@
 #!/bin/sh
 #
-# Tag all project files.
+# Move (rename) a tag from all project files.
 #
-# File:		cvstag
+# File:		cvstagmv
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Tue Mar 31 04:44:00 EDT 2009
+# Date:		Tue Mar 31 05:12:16 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -14,8 +14,8 @@
 #
 #   $Author: walton $
 #   $Date: 2009/03/31 11:02:51 $
-#   $RCSfile: cvstag,v $
-#   $Revision: 1.3 $
+#   $RCSfile: cvstagmv,v $
+#   $Revision: 1.1 $
 
 # Redirect all error output to the standard output.
 #
@@ -24,35 +24,17 @@ exec 2>&1
 case "$1" in
 -doc*)
     echo '
-cvstag tag
+cvstagmv oldtag newtag
 
     First commit (as per cvscom), then update (as per
-    cvsup), then remove the tag from all files in the
-    repository, and then tag all current project file
-    revisions with the given tag.  The tag can be any
-    symbol not beginning with a digit.
-
-    Specifically, a tag on a file is an abbreviation for
-    a particular revision of the file.  By tagging the
-    current revisions of all files in a project, you
-    tag a revision of the project as a whole.  This pro-
-    ject revision can then be checked out with cvsout
-    using the -rtag option, in order to recover the
-    tagged revision of the project.
-
-    The only way to manipulate (e.g. remove) a tag is
-    to make a temporary local copy of the current direc-
-    tory and its subdirectories that have the tagged
-    version of the files checked out, and manipulate
-    (e.g. remove) the tag in that temporary local copy,
-    and then delete the temporary local copy.  Otherwise
-    Attic files are not properly considered.'
+    cvsup), then move (rename) the tag for all files in
+    the repository.  See cvstag for more on tags.'
 
     exit 1
     ;;
 esac
 
-if [ $# -ne 1 ]
+if [ $# -ne 2 ]
 then
     echo "ERROR: too few or too many arguments"
     exit 2
@@ -63,11 +45,19 @@ then
     exit 2
 fi
 
-tag="$1"
+oldtag="$1"
+newtag="$2"
 
-case "$tag" in
+case "$oldtag" in
 [0-9]*)
-    echo "ERROR: tag cannot begin with a digit: $tag"
+    echo "ERROR: tag cannot begin with a digit: $oldtag"
+    exit 2
+    ;;
+esac
+
+case "$newtag" in
+[0-9]*)
+    echo "ERROR: tag cannot begin with a digit: $newtag"
     exit 2
     ;;
 esac
@@ -121,25 +111,48 @@ fi
 echo mkdir $tmpdir
 mkdir $tmpdir
 
-pwd="`pwd`"
+pwd=`pwd`
 
 echo cd $tmpdir
 cd $tmpdir
-echo cvs -d "$root" checkout "-r$tag" -P "$repository"
-if cvs -d "$root" checkout "-r$tag" -P "$repository" \
-   && [ -d "$repository" ]
+
+echo cvs -d "$root" checkout "-r$newtag" -P \
+	 "$repository"
+if cvs -d "$root" checkout "-r$newtag" -P \
+       "$repository" && [ -d "$repository" ]
 then
     echo cd "$repository"
     cd "$repository"
-    echo cvs tag -d "$tag"
-    cvs tag -d "$tag"
+
+    echo cvs tag -d "$newtag"
+    cvs tag -d "$newtag"
+
+    echo cd $tmpdir
+    cd $tmpdir
+
+    echo rm -rf $tmpdir/$repository
+    rm -rf $tmpdir/$repository
 fi
 
-echo rm -rf $tmpdir
-rm -rf $tmpdir
+echo cvs -d "$root" checkout "-r$oldtag" -P \
+         "$repository"
+if cvs -d "$root" checkout "-r$oldtag" -P \
+        "$repository" && [ -d "$repository" ]
+then
+    echo cd "$repository"
+    cd "$repository"
+
+    echo cvs tag "$newtag"
+    cvs tag "$newtag"
+
+    echo cvs tag -d "$oldtag"
+    cvs tag -d "$oldtag"
+fi
 
 echo cd "$pwd"
 cd "$pwd"
 
-echo cvs tag "$1"
-cvs tag "$1"
+echo rm -rf $tmpdir
+rm -rf $tmpdir
+
+exit 0
