update

diff --git a/bin/cvstag b/bin/cvstag
--- a/bin/cvstag
+++ b/bin/cvstag
@@ -4,7 +4,7 @@
 #
 # File:		cvstag
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Sun Apr  5 09:21:10 EDT 2009
+# Date:		Sun Apr  5 09:26:36 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/04/05 13:21:27 $
+#   $Date: 2009/04/05 13:26:55 $
 #   $RCSfile: cvstag,v $
-#   $Revision: 1.8 $
+#   $Revision: 1.9 $
 
 # Redirect all error output to the standard output.
 #
@@ -138,7 +138,10 @@ mkdir $tmpdir
 pwd="`pwd`"
 
 echo cd $tmpdir
-cd $tmpdir
+if ! cd $tmpdir
+then
+    echo "ERROR: cd $tmpdir failed"
+fi
 
 echo "# Checkout with $tag tag to remove it"
 echo "# This will fail if tag was not previously used"
