update

diff --git a/bin/cvstagmv b/bin/cvstagmv
--- a/bin/cvstagmv
+++ b/bin/cvstagmv
@@ -4,7 +4,7 @@
 #
 # File:		cvstagmv
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Tue Mar 31 12:08:43 EDT 2009
+# Date:		Sun Apr  5 09:02:54 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/03/31 16:11:28 $
+#   $Date: 2009/04/05 13:40:27 $
 #   $RCSfile: cvstagmv,v $
-#   $Revision: 1.3 $
+#   $Revision: 1.4 $
 
 # Redirect all error output to the standard output.
 #
@@ -123,6 +123,8 @@ case "$repository" in
 esac
 
 tmpdir=/tmp/cvstag-tmp-$$
+echo "# Moving to $tmpdir temporarily to manipulate" \
+     "tags"
 trap "rm -rf $tmpdir" EXIT
 rm -f $tmpdir
 if [ -e $tmpdir ]
@@ -136,13 +138,19 @@ mkdir $tmpdir
 pwd=`pwd`
 
 echo cd $tmpdir
-cd $tmpdir
+if ! cd $tmpdir
+then
+    echo "ERROR: cd $tmpdir failed"
+fi
 
+echo "# Checkout with $newtag tag to remove it"
+echo "# This will fail if tag was not previously used"
 echo cvs -d "$root" checkout "-r$newtag" -P \
 	 "$repository"
 if cvs -d "$root" checkout "-r$newtag" -P \
        "$repository" && [ -d "$repository" ]
 then
+    echo "# Removing previous $newtag tag"
     echo cd "$repository"
     cd "$repository"
 
@@ -154,8 +162,12 @@ then
 
     echo rm -rf $tmpdir/$repository
     rm -rf $tmpdir/$repository
+else
+    echo "# Checkout failed to produce $repository"
 fi
 
+echo "# Checkout with $oldtag tag to move it"
+echo "# This will fail if tag was not previously used"
 echo cvs -d "$root" checkout "-r$oldtag" -P \
          "$repository"
 if cvs -d "$root" checkout "-r$oldtag" -P \
@@ -164,13 +176,18 @@ then
     echo cd "$repository"
     cd "$repository"
 
+    echo "# Adding $newtag tag"
     echo cvs tag "$newtag"
     cvs tag "$newtag"
 
+    echo "# Removing $oldtag tag"
     echo cvs tag -d "$oldtag"
     cvs tag -d "$oldtag"
+else
+    echo "# Checkout failed to produce $repository"
 fi
 
+echo "# Returning to original current directory"
 echo cd "$pwd"
 cd "$pwd"
 
