update

diff --git a/bin/cvstagrm b/bin/cvstagrm
--- a/bin/cvstagrm
+++ b/bin/cvstagrm
@@ -4,7 +4,7 @@
 #
 # File:		cvstagrm
 # Author:	Bob Walton <walton@acm.org>
-# Date:		Fri Apr  3 21:05:26 EDT 2009
+# Date:		Sun Apr  5 09:40:46 EDT 2009
 #
 # The authors have placed this program in the public
 # domain; they make no warranty and accept no liability
@@ -13,9 +13,9 @@
 # RCS Info (may not be true date or author):
 #
 #   $Author: walton $
-#   $Date: 2009/04/04 01:06:29 $
+#   $Date: 2009/04/05 13:54:16 $
 #   $RCSfile: cvstagrm,v $
-#   $Revision: 1.3 $
+#   $Revision: 1.4 $
 
 # Redirect all error output to the standard output.
 #
@@ -105,6 +105,8 @@ case "$repository" in
 esac
 
 tmpdir=/tmp/cvstag-tmp-$$
+echo "# Moving to $tmpdir temporarily"
+echo "  to remove $tag tag"
 trap "rm -rf $tmpdir" EXIT
 rm -f $tmpdir
 if [ -e $tmpdir ]
@@ -118,19 +120,28 @@ mkdir $tmpdir
 pwd=`pwd`
 
 echo cd $tmpdir
-cd $tmpdir
+if ! cd $tmpdir
+then
+    echo "ERROR: cd $tmpdir failed"
+fi
 
+echo "# Checkout with $tag tag to remove it"
+echo "# This will fail if it was not previously used"
 echo cvs -d "$root" checkout "-r$tag" -P "$repository"
 if cvs -d "$root" checkout "-r$tag" -P "$repository" \
    && [ -d $repository ]
 then
+    echo "# Removing $tag tag"
     echo cd "$repository"
     cd "$repository"
 
     echo cvs tag -d "$tag"
     cvs tag -d "$tag"
+else
+    echo "# Checkout failed to produce $repository"
 fi
 
+echo "# Returning to original current directory"
 echo cd "$pwd"
 cd "$pwd"
 
